### ISSUE TITLE
Invalid example code?

### ISSUE THREAD

**Issue by analyst74** [ansman/validate.js#141]
Hello, I'm experiencing some strange problem with date only validation and believe the problem is in validate.js itself.

One of the problematic scenarios is when following conditions are met:
- date validation with earliest criteria set to moment.utc(), with the goal being to ensure value is today at earliest
- value to be validated is a date string from today, i.e. '2016-06-26'
- current timezone is EDT(-4)
- validation happens after 8pm
- everything else is written according to the doc

This triggers validation error saying date should be no earlier than 2016-06-27, presumably due to utc time conversion.

If I find time, I'll add a PR to show case the issue, and possibly a fix.

**Comment by analyst74** [comment]
my bad, it only returns NaN if it's an invalid date

**Comment by ansman** [comment]
Internally validate.js only works with unix timestamps.
It sound like you don't want to parse using UTC since you want to consider time zones.

**Comment by analyst74** [comment]
I managed to create a fiddle to illustrate the problem: https://jsfiddle.net/analyst74/970yky2v/1/

**Comment by analyst74** [comment]
logically, it seems if I use all local time instead of UTC, this problem will go away. however there is a line in validate.js to ensure value must be a whole date(https://github.com/ansman/validate.js/blob/master/validate.js#L897), meaning that I must parse date value using utc.

**Comment by ansman** [comment]
My bad, the correct solution is to keep parsing the dates as UTC but don't specify the earliest date as this: `moment.utc().toString("YYYY-MM-DD")`

It's hard for validate.js to work correctly with timezones since it has no date lib dependency.
The problem comes from that `2016-06-28T01:00+02:00` actually the day `2016-06-27` in UTC.

Perhaps the contract should be clearer but when you are using `dateOnly` it will always compare the UTC days.
