### ISSUE TITLE
Improper format for message with {format: "flat"}

### ISSUE THREAD

**Issue by DPechacek** [ansman/validate.js#67]
I am using the plugin with the {format: "flat"} flag.  Instead of getting just my expected error message of "Invalid characers entered.", I am getting the name of the constraint followed by my error message.  The documentation page states that with the format flat flag set, I should just get the error message.

**Comment by ansman** [comment]
Flat means you get an array with the errors back instead of getting them back in an object grouped by attribute.

You're looking for the **fullMessages** option:
```javascript
var constraints = {
  username: {
    presence: true
  }
};

validate({}, constraints);
// => {"username": ["Username can't be blank"]}

validate({}, constraints, {fullMessages: false});
// => {"username": ["can't be blank"]}
```

Though I would image you're more interested in prefixing the message with `^` which makes the message be returned as is rather than be prefixed by the attribute name:
```javascript
var constraints = {
  username: {
    presence: {
      message: "^Is required";
    }
  }
};

validate({}, constraints, {fullMessages: false});
// => {"username": ["Is required"]}
```

**Comment by DPechacek** [comment]
Thank you.  The documentation just doesn't state that you're going to get back the name of validation constraint in the message as well.
