### ISSUE TITLE
No documentation for `runValidations`

### ISSUE THREAD

**Issue by nathanboktae** [ansman/validate.js#82]
I was looking for the ability to run validations to get all validation failures, and didn't see any in the docs, but from the unit tests saw that `runValidations` exists and can do that for me, but it is nowhere to be found in the documentation.

**Comment by ansman** [comment]
The validate.js API is fairly stable but only the methods documented has a maintained backward compatibility.

The reason why I haven't hidden the implementation in a closure is that I have a strong hatred for libraries that does that since it means you cannot fix bugs without either making a fork och waiting for a new release.

What exactly are you trying to accomplish? `runValidations` is not really meant for outside use.
You can however use the `format: "detailed"` to get more information if that is what you want:
```javascript
var constraints = {
  password: {
    presence: true,
    length: {
      minimum: 6,
      message: "must be at least 6 characters"
    }
  }
};

validate({password: "bad"}, constraints, {format: "detailed"})
// => [
//   {
//     "attribute": "password",
//     "value": "bad",
//     "validator": "length",
//     "globalOptions": {
//       "format": "detailed"
//     },
//     "attributes": {
//       "password": "bad"
//     },
//     "options": {
//       "minimum": 6,
//       "message": "must be at least 6 characters"
//     },
//     "error": "Password must be at least 6 characters"
//   }
// ]
```

**Comment by nathanboktae** [comment]
`validate` only gives the first validation failure. I want all failures as an array of strings or for detailed, an `error` with an array of strings.

BTW I totally agree with your philosophy, mainly to support use cases that were missed (like this one).

**Comment by ansman** [comment]
`validate` should return all failures, how are you using it?

**Comment by nathanboktae** [comment]
You're right it does return all failures - `numericality` didn't fail on null like I thought it would, so I got confused.

Closing since this is a private API as you say, and my requirement for using it is gone. Thanks!
