### ISSUE TITLE
Is there a fail-fast option?

### ISSUE THREAD

**Issue by egmanoj** [ansman/validate.js#86]
Consider the following constraint:

```js
var constraints = {
    name: {
        presence: true,
        format: {
            pattern: /^a.*$/,
            message: "Must start with a"
        },
        length: {
            maximum: 4
        }
    }
}
```

Validating `{ name: "9aaaaa" }` using this constraint returns two error messages. 

```js
["Name Must start with a", "Name is too long (maximum is 4 characters)"]
```

Is there a fail-fast option? I.e. stop at the first error (in this case "Name Must start with a") and return just one error message?

**Comment by ansman** [comment]
Sadly not, but if you specify `{format: "detailed"}` in the options when validating you can inspect the options and not show one error if another is present.

**Comment by jesusgp22** [comment]
Adding +1 to this since sometimes it's useful to show a "This field is required" message if the field is empty (presense true and allowEmpty false) and only if something is in the field provide an "Invalid value" message

as a proposal each validator key could have an order attribute like:

field: {
   presence: true,
   numericality: {
       greaterThan: 0,
   }
   order: ['presence', 'numericality', 'numericality.greaterThan' ],
}
